### ISSUE TITLE
Symmetric support

### ISSUE THREAD

**Issue by GitHubbeer** [pghysels/STRUMPACK#111]
Greetings,

I am wondering if STRUMPACK supports symmetric solvers (using POTRF routines, and so on) now. My friend [Jie Ren](https://jieren98.github.io) wants me to finish the symmetric support and he has already implemented a basic symmetric + GPU version. So if STRUMPACK does not have a symmetric solver, I am happy to finish it based on Jie's code.

Best,
Tingxuan

**Comment by JieRen98** [comment]
https://github.com/pghysels/STRUMPACK/pull/112
