### ISSUE TITLE
CSRGraph.hpp and -DSTRUMPACK_USE_MPI=OFF

### ISSUE THREAD

**Issue by derpda** [pghysels/STRUMPACK#24]
# Issue
When building with -DSTRUMPACK_USE_MPI=OFF, the build fails due to the following line:

https://github.com/pghysels/STRUMPACK/blob/634c6ba1c7950ccc8d725c7eb3eb56bf79df3c73/src/sparse/CSRGraph.hpp#L38

The "misc/MPIWrapper.hpp" header is included, but this fails on systems without MPI headers in the path. If MPI is installed and in the path but the user decides not to use it, compiling will work, but linking will not work since MPI is (of course) not linked against due to -DSTRUMPACK_USE_MPI=OFF.

# Suggestion
Changing above line to check for STRUMPACK_USE_MPI like in other places in the code:
```cpp
#if defined(STRUMPACK_USE_MPI)
#include "misc/MPIWrapper.hpp"
#endif
```

# Result
I was able to build with -DSTRUMPACK_USE_MPI=OFF on a system with and without MPI installed after making the small change.

**Comment by pghysels** [comment]
Thank you for reporting!
I believe that line can be removed.

Pieter

**Comment by derpda** [comment]
Fair enough, I didn't even try that!

**Comment by derpda** [comment]
I just saw the new commit, thank you for that!
Closing.
