### ISSUE TITLE
Add Fortran bindings

### ISSUE THREAD

**Issue by sethrj** [pghysels/STRUMPACK#28]
Hi! @xiaoyeli and I chatted this morning at ECP about using [SWIG-Fortran](https://github.com/swig-fortran/swig), which underpins [ForTrilinos](https://github.com/trilinos/ForTrilinos), to automatically generate Fortran-2003 bindings for STRUMPACK.

I'm creating this issue to see if this is a good direction to go and track progress. The process of generating wrappers is *automated*, not quite *automatic*, so it'll have to be done in stages. If you can point me to some of the lower-level classes that would make a good example, I can get started with demonstrating what the SWIG interface file (input) and generated bindings (output) look like. I could also throw SWIG at the flat wrapper `StrumpackSparseSolver.h` to show you what that would look like.

**Comment by pghysels** [comment]
Dear Seth,

Thank you for reaching out and my apologies for the late reply. At the moment we do not have any Fortran interfaces. The ```StrumpackSparseSolver.h``` wrapper is a C interface to the C++ solver classes. This sometimes lags a bit behind the C++ interface. If ForTrilinos can work directly on the C++ interface, I think that would be better. The main interface for the sparse solver is in ```StrumpackSparseSolver.hpp```.

**Comment by sethrj** [comment]
No problem for the delay! I thought from my conversation with Sherry that there was an initial effort to expose to Fortran but I must have misunderstood.

I think the work on ForTrilinos will provide a good starting point for this, since it too has matrix construction and manipulation. I'll whip up a demo some point in the next week or two and send it your way. Do you have any interested Fortran users, or is this an open-ended capability?

**Comment by pghysels** [comment]
Thanks. Yes, we have some users who have expressed interest in a Fortran interface.

**Comment by sethrj** [comment]
For reference: the "flat" code in the PR was integrated into master in commit https://github.com/pghysels/STRUMPACK/commit/8b6218947edf37aacd4094e989057cdb5cbab743
