### ISSUE TITLE
The instruction about SLATE is missing

### ISSUE THREAD

**Issue by nindanaoto** [pghysels/STRUMPACK#34]
Hello, maintainers.

 I've tried to use STRUMPACK with SLATE to use CUDA support in the MPI setting and found that SLATE's ScaLAPACK API is uncommented in CMakeList.txt in current SLATE repository. 

 If STRUMPACK can only work with specific version of SLATE, please add instruction. It might be very helpful.

**Comment by pghysels** [comment]
I will update the instructions for building with SLATE.
But I just built the latest git version of SLATE and STRUMPACK without issues.
STRUMPACK does not use the scalapack API from SLATE, it uses SLATE's C++ API.

**Comment by nindanaoto** [comment]
Thank you for your quick reply.

 If so, I think you should remove libslate_scalapack_api.so from this line.
https://github.com/pghysels/STRUMPACK/blob/f4786b16483fb1e3ad59fc5ee8c606a2aed3edcd/example_build.sh#L50

 I could build STRUMPACK with SLATE. I'll close this issue but if you can add the official instruction, it'll be very useful for users;)

**Comment by pghysels** [comment]
Done. Thank you for the feedback.
In the near future we will improve the detection of SLATE in STRUMPACKs CMake build. But last time I checked SLATE did not have a proper CMake installation option.
