### ISSUE TITLE
STRUMPACKKernel

### ISSUE THREAD

**Issue by StefanoCipolla** [pghysels/STRUMPACK#42]
Hello!

I am trying to run the example KernelRegression.py but I receive a ''Segmentation fault (core dumped)'' error. In particular, this is the output of the command ``python KernelRegression.py'':

Usage: python3 KernelRegression.py filename h lambda degree
   - 'filename' should refer to 4 files:
            filename_train.csv
            filename_train_label.csv
            filename_test.csv
            filename_test_label.csv
   - h: kernel width
   - lambda: regularization parameter
   - degree: ANOVA kernel degree
n = 10000 d = 8 m = 1000
C++, creating kernel: n=10000, d=8 h=1.3 lambda=3.11
Segmentation fault (core dumped)
==========================
I can add also the following results for the command ``make test''

The following tests FAILED:
	 29 - SPARSE_seq_4 (Subprocess aborted)
	 30 - SPARSE_seq_5 (Subprocess aborted)
	 31 - SPARSE_seq_6 (Subprocess aborted)
	 35 - SPARSE_seq_10 (Subprocess aborted)
	 36 - SPARSE_seq_11 (Subprocess aborted)
	 37 - SPARSE_seq_12 (Subprocess aborted)
	 41 - SPARSE_seq_16 (Subprocess aborted)
	 42 - SPARSE_seq_17 (Subprocess aborted)
	 43 - SPARSE_seq_18 (Subprocess aborted)
	 47 - SPARSE_seq_22 (Subprocess aborted)
	 48 - SPARSE_seq_23 (Subprocess aborted)
	 49 - SPARSE_seq_24 (Subprocess aborted)
	 53 - SPARSE_seq_28 (Subprocess aborted)
	 54 - SPARSE_seq_29 (Subprocess aborted)
	 55 - SPARSE_seq_30 (Subprocess aborted)
	 59 - SPARSE_seq_34 (Subprocess aborted)
	 60 - SPARSE_seq_35 (Subprocess aborted)
	 61 - SPARSE_seq_36 (Subprocess aborted)
	 65 - SPARSE_seq_40 (Subprocess aborted)
	 66 - SPARSE_seq_41 (Subprocess aborted)
	 70 - SPARSE_seq_45 (Subprocess aborted)
	 71 - SPARSE_seq_46 (Subprocess aborted)
	 72 - SPARSE_seq_47 (Subprocess aborted)
Errors while running CTest
Makefile:91: recipe for target 'test' failed
make: *** [test] Error 8

=======================

Thank you very!

Stefano

**Comment by pghysels** [comment]
Dear Stefano,
My apologies for the delay.
These tests should not, they work here. Maybe there is something wrong with your setup, like with the libraries you link to.
Could you share the output of the cmake configure step for STRUMPACK?

Pieter

**Comment by StefanoCipolla** [comment]
Dear Pieter,
please find the screenshot of the cmake output!
![cmake](https://user-images.githubusercontent.com/56341866/107747123-e2626100-6d0e-11eb-9909-5a53f6f1cc04.png)

Thank you very much for your help!

Stefano

**Comment by pghysels** [comment]
Sorry for the delay again. I cannot reproduce this here.

My output looks like:
```
n = 10000 d = 8 m = 1000
# C++, creating kernel: n=10000, d=8 h=1.3 lambda=3.11
# ANN search quality = 0.920937 after 5 iterations
HSS KernelRR quality = 79.4 %
classes: [-1.  1.]
```

I assume you are on ubuntu?
Can you tell me which ubuntu version and which python version you are using?
Also, what version of sklearn (sci-kit learn)?

**Comment by StefanoCipolla** [comment]
Dear Pieter,
the required information:
====
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
====
Python 3.8.3
====
The scikit-learn version is 0.23.1.
====
Thank you very much for your help!
Stefano

**Comment by pghysels** [comment]
Hi Stefano,
I'm sorry for the delay.
I think this commit fixes the issue: https://github.com/pghysels/STRUMPACK/commit/8d0b9e2710ea0db5109c79b9b18e0df0817aa10c

**Comment by StefanoCipolla** [comment]
Dear Pieter,
now it works perfectly!
Thank you very much for your help!
Very best Regards
Stefano
![Screenshot from 2021-04-01 19-16-55](https://user-images.githubusercontent.com/56341866/113337137-44a70d80-931f-11eb-8fc2-35312edadf61.png)
