### ISSUE TITLE
Failed compilation of STRUMPACK 6.3.0

### ISSUE THREAD

**Issue by dimitargslavchev** [pghysels/STRUMPACK#53]
Hello,

I have found two issues:
1. I get the following error:
````
CMake Error at cmake/Modules/FindMETIS.cmake:168 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:379 (find_package)
````

This one easily fixable using the method from here https://github.com/facebook/rocksdb/issues/1230

I.e. I went to cmake/Modules/FindMETIS.cmake:168 and put " around the last argument of string

2. After doing the above cmake runs, but now I have compilation errors:

````
In file included from /home/dslavchev/NuclearTesting/software/STRUMPACK-6.3.0/src/sparse/ordering/MetisReordering.hpp:35,
                 from /home/dslavchev/NuclearTesting/software/STRUMPACK-6.3.0/src/sparse/CSRGraph.cpp:34:
/home/dslavchev/.local/include/metis.h:93:9: error: ‘SCOTCH_Num’ does not name a type
   93 | typedef SCOTCH_Num          idx_t;
      |         ^~~~~~~~~~
In file included from /home/dslavchev/NuclearTesting/software/STRUMPACK-6.3.0/src/sparse/CSRGraph.cpp:34:
/home/dslavchev/NuclearTesting/software/STRUMPACK-6.3.0/src/sparse/ordering/MetisReordering.hpp:47:16: error: ‘idx_t’ was not declared in this scope; did you mean ‘id_t’?
   47 |   (std::vector<idx_t>& xadj, std::vector<idx_t>& adjncy,
      |                ^~~~~
      |                id_t
````

Below is the full output and the script I use.
MKL is 2022, metis 5.1.0, parmetis 4.0.3, scotch 7.0.1 and gcc is 9.3.0

[cmake_failure_dslavchev.txt](https://github.com/pghysels/STRUMPACK/files/8176879/cmake_failure_dslavchev.txt)
[dslavche_build.sh.zip](https://github.com/pghysels/STRUMPACK/files/8176880/dslavche_build.sh.zip)

**Comment by dimitargslavchev** [comment]
OK, my error.

Real issue was that scotch installs it's own metis.h header, that mangles the original metis.h header.
Solution is to either install them in separate folders or to pass an option to scotch to not create the metis.h.

I have the strange feeling of deja vu with this one.

**Comment by pghysels** [comment]
Yes, this is annoying.  I install scotch in a local folder and just delete the metis.h file, because even if they are installed in separate folders, you don't know which one will be searched first.
I mentioned this to the Scotch developers. The latest scotch release (7.0) uses CMake and has an option `INSTALL_METIS_HEADERS` which you can set to OFF.

**Comment by dimitargslavchev** [comment]
I ended up using the INSTALL_METIS_HEADERS option.

Ideally you may detect that the wrong the metis.h is used and issue a warning in the FindMETIS script. But I don't know cmake enough to suggest how.
