### ISSUE TITLE
A C++ question about the implement of "create_frontal_matrix" in "FrontFactory.cpp"

### ISSUE THREAD

**Issue by chengpengzhao** [pghysels/STRUMPACK#54]
After I saw the source code of [FrontFactory.cpp](https://github.com/pghysels/STRUMPACK/blob/master/src/sparse/fronts/FrontFactory.cpp), I have a question about the pointer `front`:  

Its type is `FrontalMatrix`, but it's reset by a derived class ` FrontalMatrixXXX`.   
I'm not so familiar with C++ but as I know, a base class pointer isn't able to access its derived class member.   
So  I can't understand here how could `front` visit members in its derived class(like F11_, F12_ ).  
Could you teach me is there any C++ techniques used here? Thanks very much.

**Comment by pghysels** [comment]
Yes, front is a `FrontalMatrix` pointer. 
The `FrontalMatrix` class is an abstract base class, with several virtual routines, which are implemented in the derived classes, such as `FrontalMatrixDense`, `FrontalMatrixBLR` etc.
For instance
`virtual void multifrontal_factorization(...) = 0`
is a purely virtual function defined in `FrontalMatrix`, then implemented in the derived classes.
When you call `front->multifrontal_factorization(...);`
it will call the correct function from one of the subclasses, using the virtual function table (vtable).

**Comment by chengpengzhao** [comment]
You perfectly cleared my doubt 👍
