### ISSUE TITLE
Build error for Fortran 

### ISSUE THREAD

**Issue by Guoqimar** [pghysels/STRUMPACK#58]
**I tried to build an Fortran example in STRUMPACK example file. But I got the error like this:**

[login-3 build]$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kunet.ae/100059846/strum/build
[login-3 build]$ make
[ 50%] Linking CXX executable fexample
/lib/../lib64/crt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
make[2]: *** [CMakeFiles/fexample.dir/build.make:126: fexample] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/fexample.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by Guoqimar** [comment]
**I tried mannually generate exucutable code by following command:**

filename=fexample
mpiifort -O2 -xHost -nofor-main -DBLR_MT -qopenmp -c $filename.f90 -o $filename.o

mpiifort -o $filename -O2 -xHost -nofor-main -qopenmp $filename.o -lmpi -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lpthread -lparmetis -lmetis -lptscotch -lptscotcherr -lscotch -lstrumpack

**But there countless errors like**

  CSRMatrix.cpp:(.text._ZN9strumpack9CSRMatrixIdxE11read_binaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9strumpack9CSRMatrixIdxE11read_binaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1f81): undefined reference to `__cxa_end_catch'
  CSRMatrix.cpp:(.text._ZN9strumpack9CSRMatrixIdxE11read_binaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9strumpack9CSRMatrixIdxE11read_binaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1f96): undefined reference to `operator delete(void*, unsigned long)'

**Comment by pghysels** [comment]
The examples in the `examples` folder can be build as part of STRUMPACK, by running
`make examples`
in the build folder.

If you want to build an example yourself, what does your CMakeLists.txt file look like? 
It should be something like:
```
cmake_minimum_required(VERSION 3.17)
project(myapp LANGUAGES Fortran)
find_package(STRUMPACK REQUIRED)
add_executable(fexample fexample.f90)
target_link_libraries(fexample PRIVATE STRUMPACK::strumpack)
```

For the manual command, I think you need to link with the C++ standard library. Try adding `-lstdc++`

**Comment by Guoqimar** [comment]
@pghysels 
**Hi，in fact I copied the feample.f90 to my own file to compile, the compilation is successful, but link failed like this**
[@login-3 build]$ make
[ 50%] Linking CXX executable fex
/lib/../lib64/crt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
make[2]: *** [CMakeFiles/fex.dir/build.make:120: fex] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/fex.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Do you mean this fortran code is not working if it is put out of the example file? I have tried to run a C++ code from the example file as well, it is working as usual using my Cmakelists.txt, but for frotran code the error always happens. BTW, I tried manually link by adding -stdc++, there still lots of errors but less than before. Thank you.**

**Comment by Guoqimar** [comment]
@pghysels  **I mute all the lines of this fortran code but several lines like below,  I think it is not the problem of code. But another c++ code named testPoisson2d is working well. This is confusing.**

program fexample
  use, intrinsic :: ISO_C_BINDING
  use strumpack
  implicit none
 .
.
.
 write(*,*) 'Finish example----------------------------------'
end program fexample

**Comment by Guoqimar** [comment]
@pghysels  **I just found that if I mute all the lines of this fortran code but several lines like below,  I can mannually compile and link successfully. But 'make' still fail like before.  If I keep one call strumpack subroutine, mannually link is also not working**  

program fexample
use, intrinsic :: ISO_C_BINDING
use strumpack
implicit none
.
.
.
write(,) 'Finish example----------------------------------'
end program fexample

**Comment by Guoqimar** [comment]
@pghysels  Now the link is working. Thank you very much.

**Comment by Guoqimar** [comment]
@pghysels  BTW, I also make it work by mannual link, I never thought it is the sequence of linking flags. Thanks
