### ISSUE TITLE
Complex-valued implementation of SparseSolver, (2) Mapping from C++ to  Fortran

### ISSUE THREAD

**Issue by Guoqimar** [pghysels/STRUMPACK#61]
**Hi thanks for your previous help. I would also like to ask if it is different between real- and complex-valued linear equations when using SparseSolver. Because I tried changing the real matrix in fexample.f90 (of example folder) to complex type, whereas I got errors like:**

Intel MKL ERROR: Parameter 6 was incorrect on entry to DLASWP.

**(2) Another important question is still about the different calls between C and fortran I asked yesterday. For example, in documentation, I guess the mapping relationship is as** 

 StrumpackSparseSolver<double> sp;    // create solver object  =====> (Fortran) type(STRUMPACK_SparseSolver) :: sp  
 sp.options().set_rel_tol(1e-10);   // set options    =====> (Fortran) ??   Hope give an example
 sp.reorder();   // reorder matrix                            =====> (Fortran) ??  is it  sp%reorder='metis' 

**In fact, this mapping is the main difficult for me, I expect there are mentions in documentation, but there seems not.**

**Comment by pghysels** [comment]
Yes, changing real to complex should still just work. But you need to change the precision when you create the solver:
```
call STRUMPACK_init_mt(S, STRUMPACK_DOUBLECOMPLEX, STRUMPACK_MT, 0, c_null_ptr, 1)
```

Look at fexample.f90 in the examples folder and at src/fortran.strumpack.f90.
```
call STRUMPACK_set_rel_tol(S, dble(1.e-10));
ierr = STRUMPACK_reorder(S)
```

**Comment by Guoqimar** [comment]
@pghysels Thanks for your answer. 

 When I run complex-valued linear equation, it works but just only half of X has solutions and the rest half are all zeros. I checked real-valued case, the solution is correct. Do you have any ideas about this problem?

**Comment by pghysels** [comment]
Can you show me some code?

**Comment by Guoqimar** [comment]
@pghysels Hi，  I copy the full code showing below
program fexample
  use, intrinsic :: ISO_C_BINDING
  use strumpack
  implicit none

  integer(c_int) :: k      ! grid dimension
  integer, target :: n     ! matrix dimension
  integer :: nnz           ! matrix nonzeros
  integer :: r, c, i       ! row, column, index
  integer(c_int) :: ierr,Ret

  ! compressed sparse row representation
  integer, dimension (:), allocatable, target :: rptr, cind
  complex(kind=16), dimension(:), allocatable, target :: val

  ! solution and right hand-side vectors
  complex(kind=16), dimension(:), allocatable, target :: x, b

  ! sparse solver object
  type(STRUMPACK_SparseSolver) :: S

  k = 400
  write(*,*) "# Solving a ", k, "^2 Poisson problem\n"

  call STRUMPACK_init_mt(S, STRUMPACK_DOUBLECOMPLEX, STRUMPACK_MT, 0, c_null_ptr, 1)
!

  call STRUMPACK_set_rel_tol(s, 0.005)
  call STRUMPACK_set_abs_tol(s, 1.0D-11)

  call STRUMPACK_set_gmres_restart(s, 1)
  ! The 2d Poisson problem does not need static pivoting, the matrix
  ! is already diagonally dominant.
!  call STRUMPACK_set_matching(S, STRUMPACK_MATCHING_NONE);

  ! Since we are defining the problem on a regular k^2 grid, we can
  ! use a geometric nested dissection ordering, but then we need to
  ! specify the grid dimension, see below.
!  call STRUMPACK_set_reordering_method(S, STRUMPACK_GEOMETRIC);
  ! Alternatively, use metis or scotch:
  ! call STRUMPACK_set_reordering_method(S, STRUMPACK_METIS);

  ! Set compression method. Other options include NONE, HSS, HODLR,
  ! LOSSY, LOSSLESS. HODLR is only supported in parallel, and only
  ! supports double precision (including complex double).

  call STRUMPACK_set_compression(S, STRUMPACK_BLR);

  ! Set the block size and relative compression tolerances for BLR
  ! compression.
  call STRUMPACK_set_compression_leaf_size(S, 64);
  call STRUMPACK_set_compression_rel_tol(S, dble(1.e-2));

  ! Only sub-blocks in the sparse triangular factors corresponing to
  ! separators larger than this minimum separator size will be
  ! compressed. For performance, this value should probably be larger
  ! than 128. This value should be larger for HODLR/HODBF, than for
  ! BLR, since HODLR/HODBF have larger constants in the complexity.
  ! For an n x n 2D domain, the largest separator will correspond to
  ! an n x n sub-block in the sparse factors.
  call STRUMPACK_set_compression_min_sep_size(S, 300);

  n = k * k
  nnz = 5 * n - 4 * k
  allocate(rptr(n+1)) ! row pointers (start of each row in cind and val)
  allocate(cind(nnz)) ! column indices
  allocate(val(nnz))  ! nonzero values

  ! Construct a compressed sparse row representation of a sparse
  ! matrix corresponding to a 5-point stencil, i.e., a second order
  ! finite difference scheme, for the 2-d Poisson equation.
  nnz = 1
  rptr(1) = 0
  do r = 0, k-1
     do c = 0, k-1
        i = c + k * r
        val(nnz) = (4.0,4.0)
        cind(nnz) = i
        nnz = nnz + 1
        if (c > 0) then      ! left
           val(nnz) = (-1.0,-1.0)
           cind(nnz) = i - 1
           nnz = nnz + 1
        end if
        if (c < k-1) then    ! right
           val(nnz) = (-1.0,-1.0)
           cind(nnz) = i + 1
           nnz = nnz + 1
        end if
        if (r > 0) then      ! up
           val(nnz) = (-1.0,-1.0)
           cind(nnz) = i - k
           nnz = nnz + 1
        end if
        if (r < k-1) then    ! down
           val(nnz) = (-1.0,-1.0)
           cind(nnz) = i + k
           nnz = nnz + 1
        end if
        rptr(i+2) = nnz - 1
     end do
  end do

  allocate(b(n))
  allocate(x(n))
  do i = 1, n
     b(i) = (1.0,1.0)
     x(i) = (0.0,0.0)
  end do

  call STRUMPACK_set_csr_matrix &
       (S, c_loc(n), c_loc(rptr), c_loc(cind), c_loc(val), 1);

  ! use geometric nested dissection
!  ierr = STRUMPACK_reorder_regular(S, k, k, 1)
   call STRUMPACK_set_reordering_method(S, STRUMPACK_metis)
  ! Solve will internally call factor (and reorder if necessary).
  ierr = STRUMPACK_solve(S, c_loc(b), c_loc(x), 0);
  do I=1,N
  print*,x(i),I
  enddo

end program fexample

**Comment by Guoqimar** [comment]
@pghysels Dr. Pghysels, could you please take a look at that? Is it possible there is a problem with the Subroutine?

**Comment by pghysels** [comment]
Try `complex(kind=8)` instead of `complex(kind=16)` for double precision complex numbers.

**Comment by Guoqimar** [comment]
Thank you very much, surely it is because that. I feel sorry to bother you with such silly problem. Have a nice day.
