### ISSUE TITLE
Spack installation failure

### ISSUE THREAD

**Issue by AlexGKim** [pghysels/STRUMPACK#66]
Installation using Spack has error

Using the commands

```
git clone https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
spack install strumpack
```

The output file is enclosed.
[spack-build-out.txt](https://github.com/pghysels/STRUMPACK/files/9049607/spack-build-out.txt)

**Comment by pghysels** [comment]
The error seems unrelated to STRUMPACK.
Are you able to install other packages using spack?

**Comment by AlexGKim** [comment]
Hi @pghysels.  

As a test, I have successfully installed other packages using spack.

Hints suggested that some g++ distributions for OSX may not support some syntax.

> The error message suggests that the system header files which are being included use non-standard features (blocks: ^ symbol), which gcc doesn't support, but clang does.
> Probably your best option at the moment is to use clang instead of gcc.

  Things get further along using 

`spack install strumpack%apple-clang`

but I get errors later related to linking to pre-existing g++ libraries on my laptop.

**Comment by AlexGKim** [comment]
I get a successful build when I execute.  

`spack install strumpack%apple-clang -mpi`

For my current purposes I don't need MPI.

**Comment by AlexGKim** [comment]
The `spack` installation results in
```
(base) tibia:build akim$ ./myexe 
dense 1000 x 1000 matrix
  - memory(A) = 8 MByte

===============================
 Compression from dense matrix
===============================
BLR
  - nonzeros(H) = 530000
  - memory(H) = 4.24 MByte
  - rank(H) = 250
  - ||A-H||_F/||A||_F = 3.81149e-05
BLR failed: Operation factor not supported for this type.
HSS
  - nonzeros(H) = 160576
  - memory(H) = 1.21334 MByte
  - rank(H) = 14
  - ||A-H||_F/||A||_F = 1.90661e-05
  - ||X-H\(H*X)||_F/||X||_F = 1.70229e-15
  - ||X-H\(A*X)||_F/||X||_F = 1.52965e-05
GMRES it. 0	res =       31.704	rel.res =            1	 restart!
...
```

**Comment by pghysels** [comment]
I don't see what could be wrong here, that results in the `Abort trap: 6`.  It seems to be related to the exception handling.
Do you see any differences in compilers used, compilation flags etc, between CMake and spack installs?

**Comment by AlexGKim** [comment]
Hi @pghysels . Apologies for the silence.  I have been experimenting with different configurations.   The problem I am encountering in`spack` is with scalapack and is due to inconsistencies with system libraries and the compiler.

To enable more control, I have successfully installed STRUMPACK with cmake.   So I am personally good though I never got things to work with spack.
