### ISSUE TITLE
[Feature Request] Sparse non-square matrices

### ISSUE THREAD

**Issue by AlexGKim** [pghysels/STRUMPACK#69]
The documentation indicates a TODO to get non-square matrices working for CompressedSparseMatrix.  I affirm that such functionality would be helpful for my application.

**Comment by pghysels** [comment]
What would be the use case for that?
The CompressedSparseMatrix class and it's derived implementations are mainly used internally for the sparse factorization. We don't plan to support factorization of non-square sparse matrices, so we don't really have a need to implement this for now.

If all you need is a sparse matrix times vector product, you could implement a compressed sparse row/column data structure yourself with 3 arrays. You can then use optimized MKL or cusparse routines.

**Comment by AlexGKim** [comment]
@pghysels .  Indeed it is the latter matrix multiplication that we need.  We will look into this.
