### ISSUE TITLE
API question: local submatrix of DistributedMatrix

### ISSUE THREAD

**Issue by AlexGKim** [pghysels/STRUMPACK#79]
I would like to get the locally stored submatrix of a `DistributedMatrix`.  The API shows a method `gather()` but with no further description.  Is this the appropriate method or is there another access point?  Otherwise, I note that a matrix could be constructed from `data()`.

**Comment by pghysels** [comment]
There is 
```
dense()
dense_and_clear()
dense_wrapper()
```
the first one returns a copy of the local submatrix as a `DenseMatrix`. The second one returns the local submatrix as a `DenseMatrix` and clears the DistributedMatrix. The last one returns a `DenseMatrixWrapper` which refers to the local submatrix.

**Comment by pghysels** [comment]
`gather()` will gather the different pieces of the entire `DistributedMatrix` into a single matrix to a single MPI rank and return that as a `DenseMatrix`.

**Comment by AlexGKim** [comment]
Got it, thanks!
