### ISSUE TITLE
Linking to Accelerate does not work: missing _clapmr_, _zlapmr_, _slapmr_, _dlapmr_

### ISSUE THREAD

**Issue by barracuda156** [pghysels/STRUMPACK#84]
Apparently these symbols are not there:
```
Undefined symbols:
  "_zlapmr_", referenced from:
      __ZN9strumpack4blas5lapmrEbiiPSt7complexIdEiPKi in libstrumpack.a(BLASLAPACKWrapper.cpp.o)
  "_dlapmr_", referenced from:
      __ZN9strumpack4blas5lapmrEbiiPdiPKi in libstrumpack.a(BLASLAPACKWrapper.cpp.o)
  "_clapmr_", referenced from:
      __ZN9strumpack4blas5lapmrEbiiPSt7complexIfEiPKi in libstrumpack.a(BLASLAPACKWrapper.cpp.o)
  "_slapmr_", referenced from:
      __ZN9strumpack4blas5lapmrEbiiPfiPKi in libstrumpack.a(BLASLAPACKWrapper.cpp.o)
ld: symbol(s) not found
```

And indeed it does look like that:
```
10:~ svacchanda$ nm -arch ppc -g /usr/lib/libLAPACK.dylib | grep _clapm
00204e20 T _clapmt
00204e20 T _clapmt_
```

Linking to OpenBLAS works, but a number of tests are broken: https://github.com/pghysels/STRUMPACK/issues/83

**Comment by pghysels** [comment]
I just added the lapack sources for xlapmr in this commit: https://github.com/pghysels/STRUMPACK/commit/0eb14778097bab4fef6e04bcc50b51a6ef00d2fe
Can you check if it is working now with Accelerate?

**Comment by barracuda156** [comment]
> I just added the lapack sources for xlapmr in this commit: [0eb1477](https://github.com/pghysels/STRUMPACK/commit/0eb14778097bab4fef6e04bcc50b51a6ef00d2fe)
> Can you check if it is working now with Accelerate?

Thank you! I will try now.

**Comment by barracuda156** [comment]
@pghysels Yes, linking to Accelerate now works, thanks again.
