### ISSUE TITLE
Group size after applying binary_tree_clustering

### ISSUE THREAD

**Issue by Zqinghaohh** [pghysels/STRUMPACK#85]
Hi, I'm using binary_tree_clustering to partition mesh. However, after it modifies the data matrix and returns a binary tree, I have no idea how to specify each cluster size.

For example, we have 10 data points and we would like to partition them into 3 groups. So how could I determine how many data points in each group? (Maybe through the returned binary tree? But how?)

**Comment by pghysels** [comment]
The `ClusterTree` (see `src/structured/ClusterTree.hpp`) has a routine 
`leaf_sizes()` which returns a vector with the sizes of the clusters.
