### ISSUE TITLE
Access elements in HODLRMatrix

### ISSUE THREAD

**Issue by Zqinghaohh** [pghysels/STRUMPACK#88]
Dear developers,

Could I ask if it's possible to get the elements in the HODLR compressed matrix?

Should I just get the submatrix by using extract_elements() and access the elements in the dense matrix?

Thanks,
Qinghao

**Comment by pghysels** [comment]
From the `strumpack::HODLR::HODLRMatrix` [class](https://portal.nersc.gov/project/sparse/strumpack/master/classstrumpack_1_1HODLR_1_1HODLRMatrix.html) you can use

- the `dense( const BLACSGrid * g )` routine, this returns the whole matrix as dense by multiplying out the factors. The result is a `DistributedMatrix` using 2D block cyclic layout on the grid `g`.
- `void extract_elements (const Vec_t &I, const Vec_t &J, DenseM_t &B)` will return a submatrix `H(I,J)` where `I` and `J` are `std::vector<std::size_t>`  vectors of indices. You need to make sure matrix `B` is allocated to `I.size()` rows and `J.size()` columns. In this case `B` is only returned at the root MPI process.
-  `void extract_elements (const VecVec_t &I, const VecVec_t &J, std::vector< DistM_t > &B)` or `void	extract_elements (const VecVec_t &I, const VecVec_t &J, std::vector< DenseM_t > &B)` can return multiple sub-blocks at once.

**Comment by Zqinghaohh** [comment]
Thanks a lot!!!
