### ISSUE TITLE
Inconsistant diagonal entries for dense matrix and corresponding HODLR matrix

### ISSUE THREAD

**Issue by Zqinghaohh** [pghysels/STRUMPACK#89]
Hi developers,

If I modify the example testHODLR.cpp a little bit to check the diagonal entries in HODLR matrix, but they are not the same as in the original dense matrix. I changed the element evaluation function as each entry is given by i+j.

To obtain the diagonal entries from HODLR matrix, I convert it back to a dense matrix.

Here is the code and my output:
```
int main(int argc, char **argv)
{

	MPI_Init(&argc, &argv);

	{
		// c will be a wrapper to MPI_COMM_WORLD
		MPIComm c;

		// the matrix size
		int N = 100;
		if (argc > 1) N = stoi(argv[1]);
		int nrhs = 1;

		HODLR::HODLROptions<double> opts;
		opts.set_from_command_line(argc, argv);


		// define a partition tree for the HODLR matrix
		structured::ClusterTree t(N);
		t.refine(50);

		auto Toeplitz = [](int i, int j) { return abs(i+j); };

		if (c.is_root())
			cout << "# compressing " << N << " x " << N << " Toeplitz matrix,"
			     << " with relative tolerance " << opts.rel_tol() << endl;

		// construct a HODLR representation for a Toeplitz matrix, using
		// only a routine to evaluate individual elements
		HODLR::HODLRMatrix<double> H(c, t, Toeplitz, opts);

		auto memfill = H.total_memory() / 1.e6;
		auto maxrank = H.max_rank();
        	auto HCols = H.cols();
        	auto HRows = H.rows();
		if (c.is_root())
			cout << "# H has max rank " << maxrank << " and takes "
			     << memfill << " MByte (compared to "
			     << (N*N / 1.e6) << " MByte for dense storage)"
                 		<< " And H has " << HRows << "rows and " << HCols << "columns."
			     << endl;

		//////////////////////////////////////////////////////////////////
		// extract a random submatrix from H to check the accuracy
		vector<std::size_t> I(N), J(N);
        	J[0] = 0;
        	I[0] = 0;
        	std::iota(I.begin()+1, I.end(), 1);
        	std::iota(J.begin()+1, J.end(), 1);
		c.broadcast(I);
		c.broadcast(J);
		DenseMatrix<double> B(I.size(), J.size());
		// extract H(I,J) and put in B (only on root)
		H.extract_elements(I, J, B);
        	if (c.is_root()) {
        	    for (int j=0; j<J.size(); j++)
           	     for (int i=0; i<I.size(); i++) {
          	          if (i == j) std::cout << "(i, j) = (" << i << ", " << j << ") ==> " << B(i,j)  << ", " << Toeplitz(I[i], J[j]) << std::endl;
         	           B(i, j) -= Toeplitz(I[i], J[j]);
                }
          	  cout << "# extracting a random " << I.size() << " x " << J.size()
                 << " submatrix to check accuracy" << endl
			     << "# ||H(I,J) - T(I,J)||_F = " << B.normF() << endl;
		}
	}

	MPI_Finalize();


	return 0;
}
```

```
# compressing 100 x 100 Toeplitz matrix, with relative tolerance 0.0001
 NUMBER_MPI=           1
 OMP_NUM_THREADS=           1
 HODLR_BUTTERFLY_SOLVER
    
 User-supplied kernel:
     
 Hierarchical format......
 
 Maxlevel_for_blocks:           1
 N_leaf:          50
 
 Constructing basis groups...
 Hierarchical format finished
     
 Matrix construction......
 
 SVD error threshold   1.0000000000000000E-004
 
 constructing Leaf-blocks......
 constructing level           1
 time   6.1164399999999995E-004 rankmax_of_level so far:           0           2
 constructing level           2
 time   1.0925700000000019E-004 rankmax_of_level so far:           0           2
 rankmax_of_level:           0           2
 
 Total construction time:   7.2879100000000012E-004 Seconds
 Total entry eval time:   5.6181200000000008E-004 Seconds
 Total construction flops:      5.23E+05
 time_tmp   0.0000000000000000     
 
   3.1250000000000002E-003 MB costed for butterfly forward blocks
   3.9062500000000000E-002 MB costed for direct forward blocks
 
 Matrix construction finished
 BPACK_CheckError: fnorm: 2.1267091E+04 2.1267091E+04 acc:  3.51E-16 time:  5.40E-04
# H has max rank 2 and takes 0.044236 MByte (compared to 0.01 MByte for dense storage) And H has 100rows and 100columns.
(i, j) = (0, 0) ==> 0, 0
(i, j) = (1, 1) ==> 98, 2
(i, j) = (2, 2) ==> 96, 4
(i, j) = (3, 3) ==> 94, 6
(i, j) = (4, 4) ==> 92, 8
(i, j) = (5, 5) ==> 90, 10
(i, j) = (6, 6) ==> 88, 12
(i, j) = (7, 7) ==> 86, 14
(i, j) = (8, 8) ==> 84, 16
(i, j) = (9, 9) ==> 82, 18
(i, j) = (10, 10) ==> 80, 20
(i, j) = (11, 11) ==> 78, 22
(i, j) = (12, 12) ==> 76, 24
(i, j) = (13, 13) ==> 74, 26
(i, j) = (14, 14) ==> 72, 28
(i, j) = (15, 15) ==> 70, 30
(i, j) = (16, 16) ==> 68, 32
(i, j) = (17, 17) ==> 66, 34
(i, j) = (18, 18) ==> 64, 36
(i, j) = (19, 19) ==> 62, 38
(i, j) = (20, 20) ==> 60, 40
(i, j) = (21, 21) ==> 58, 42
(i, j) = (22, 22) ==> 56, 44
(i, j) = (23, 23) ==> 54, 46
(i, j) = (24, 24) ==> 52, 48
(i, j) = (25, 25) ==> 50, 50
(i, j) = (26, 26) ==> 48, 52
(i, j) = (27, 27) ==> 46, 54
(i, j) = (28, 28) ==> 44, 56
(i, j) = (29, 29) ==> 42, 58
(i, j) = (30, 30) ==> 40, 60
(i, j) = (31, 31) ==> 38, 62
(i, j) = (32, 32) ==> 36, 64
(i, j) = (33, 33) ==> 34, 66
(i, j) = (34, 34) ==> 32, 68
(i, j) = (35, 35) ==> 30, 70
(i, j) = (36, 36) ==> 28, 72
(i, j) = (37, 37) ==> 26, 74
(i, j) = (38, 38) ==> 24, 76
(i, j) = (39, 39) ==> 22, 78
(i, j) = (40, 40) ==> 20, 80
(i, j) = (41, 41) ==> 18, 82
(i, j) = (42, 42) ==> 16, 84
(i, j) = (43, 43) ==> 14, 86
(i, j) = (44, 44) ==> 12, 88
(i, j) = (45, 45) ==> 10, 90
(i, j) = (46, 46) ==> 8, 92
(i, j) = (47, 47) ==> 6, 94
(i, j) = (48, 48) ==> 4, 96
(i, j) = (49, 49) ==> 2, 98
(i, j) = (50, 50) ==> 198, 100
(i, j) = (51, 51) ==> 196, 102
(i, j) = (52, 52) ==> 194, 104
(i, j) = (53, 53) ==> 192, 106
(i, j) = (54, 54) ==> 190, 108
(i, j) = (55, 55) ==> 188, 110
(i, j) = (56, 56) ==> 186, 112
(i, j) = (57, 57) ==> 184, 114
(i, j) = (58, 58) ==> 182, 116
(i, j) = (59, 59) ==> 180, 118
(i, j) = (60, 60) ==> 178, 120
(i, j) = (61, 61) ==> 176, 122
(i, j) = (62, 62) ==> 174, 124
(i, j) = (63, 63) ==> 172, 126
(i, j) = (64, 64) ==> 170, 128
(i, j) = (65, 65) ==> 168, 130
(i, j) = (66, 66) ==> 166, 132
(i, j) = (67, 67) ==> 164, 134
(i, j) = (68, 68) ==> 162, 136
(i, j) = (69, 69) ==> 160, 138
(i, j) = (70, 70) ==> 158, 140
(i, j) = (71, 71) ==> 156, 142
(i, j) = (72, 72) ==> 154, 144
(i, j) = (73, 73) ==> 152, 146
(i, j) = (74, 74) ==> 150, 148
(i, j) = (75, 75) ==> 148, 150
(i, j) = (76, 76) ==> 146, 152
(i, j) = (77, 77) ==> 144, 154
(i, j) = (78, 78) ==> 142, 156
(i, j) = (79, 79) ==> 140, 158
(i, j) = (80, 80) ==> 138, 160
(i, j) = (81, 81) ==> 136, 162
(i, j) = (82, 82) ==> 134, 164
(i, j) = (83, 83) ==> 132, 166
(i, j) = (84, 84) ==> 130, 168
(i, j) = (85, 85) ==> 128, 170
(i, j) = (86, 86) ==> 126, 172
(i, j) = (87, 87) ==> 124, 174
(i, j) = (88, 88) ==> 122, 176
(i, j) = (89, 89) ==> 120, 178
(i, j) = (90, 90) ==> 118, 180
(i, j) = (91, 91) ==> 116, 182
(i, j) = (92, 92) ==> 114, 184
(i, j) = (93, 93) ==> 112, 186
(i, j) = (94, 94) ==> 110, 188
(i, j) = (95, 95) ==> 108, 190
(i, j) = (96, 96) ==> 106, 192
(i, j) = (97, 97) ==> 104, 194
(i, j) = (98, 98) ==> 102, 196
(i, j) = (99, 99) ==> 100, 198
# extracting a random 100 x 100 submatrix to check accuracy
# ||H(I,J) - T(I,J)||_F = 4021.19

Process finished with exit code 0

```

**Comment by pghysels** [comment]
Hi, we looked into this. 
The problem is that the HODLR code (implemented in ButterflyPACK) applies a permutation to the matrix, and this permutation is not taken into account in `extract_elements` (or in any other routines using the HODLR matrix). 
I have modified the `HODLR::HODLRMatrix` compression routine to disable this permutation. 
See [this](https://github.com/pghysels/STRUMPACK/commit/cdaebd1452558e735421c082eace833a17e1303c) commit.
Your code should run correctly now.
However, to get good compression, you will need to permute your matrix (if it is anything more complicated than a simple Toeplitz problem). We have ordering routines [here](https://portal.nersc.gov/project/sparse/strumpack/master/namespacestrumpack.html#a90270bd51d914b3213aed9e147e25a07). These can be applied to your geometry info for instance.

Alternatively, you can also use ButterflyPACK directly. This might give you more options. See for instance [this driver](https://github.com/liuyangzhuan/ButterflyPACK/blob/master/EXAMPLE/InterfaceTest_simple.cpp).
@liuyangzhuan can help you with the ButterflyPACK driver.

**Comment by liuyangzhuan** [comment]
@Zqinghaohh  May I ask what dense matrix are you considering? 
As Pieter pointed out, [this driver](https://github.com/liuyangzhuan/ButterflyPACK/blob/master/EXAMPLE/InterfaceTest_simple.cpp) compresses a (Gaussian) kernel matrix with geometry point information (d-feature vectors as points in d-dimensional space), butterflypack will reorder the matrix based on the geometry information and return the permutation vector to the user. You can use the permutation accordingly. 

There are two ways to get the index conversion
1. d_c_bpack_construct_init(&Npo, &Ndim, dat_ptr, nns_ptr,&nlevel, tree, **perms**, &**myseg**, &bmat, &option, &stats, &msh, &kerquant, &ptree, &C_FuncDistmn, &C_FuncNearFar, quant_ptr);
perms is a length-N vector, and j=perms[i] will convert the permuted index (starting from 0 to N-1) to the original index (starting from 1 to N)
myseg is the number of low rows on my MPI rank

2. **d_c_bpack_new2old**(&msh,&i_new_loc,&i_old);
the permuted index i_new_loc that starts from 1 to myseg is converted to the original index starts from 1 to N.

**Comment by Zqinghaohh** [comment]
Thanks for your helpful replies!

@pghysels You mentioned "this permutation is not taken into account in `extract_elements`". Did you mean the matrix has been permuted when compressing it, but when we apply `extract_elements`, it did not convert back?

@liuyangzhuan I would like to apply ACA/HODLR to the solution to method of moments which induces a large dense matrix. So basically, I need to solve the system `Ax=b`.

Now I have routines to explicitly generate `A` and `b` while `A` can be represented by blocks based the partitioned geometry. So, if the compressed `A` is permuted, when I generate my RHS, should I also permute it?

**Comment by liuyangzhuan** [comment]
If you are considering a MoM application, you should take a closer look at 

https://github.com/liuyangzhuan/ButterflyPACK/blob/master/EXAMPLE/EMCURV_Driver.f90
https://github.com/liuyangzhuan/ButterflyPACK/blob/0465e0afcf8dc797d6bf4f30fa2e452ecdbacc4c/EXAMPLE/EMCURV_Module.f90#L928
for a fortran example of 2D MoM application. I don't have MoM examples in cpp, but the following is a cpp example for compressing kernel ridge regression matrices
https://github.com/liuyangzhuan/ButterflyPACK/blob/master/EXAMPLE/InterfaceTest_simple.cpp

In both cases, you can see that the rhs b and solution x are of length roughly N/P, N being matrix size and P is total MPI count. Those local vectors are already permuted, with cpp you can use the permutation vector perms returned from 
d_c_bpack_construct_init(&Npo, &Ndim, dat_ptr, nns_ptr,&nlevel, tree, perms, &myseg, &bmat, &option, &stats, &msh, &kerquant, &ptree, &C_FuncDistmn, &C_FuncNearFar, quant_ptr);

or with Fortran, you can use Permutation returned from
subroutine BPACK_construction_Init(Nunk, Permutation, Nunk_loc, bmat, option, stats, msh, ker, ptree, Coordinates, tree, nns)

to assign b and assemble the global solution vector properly. Again, look at the two examples I pointed out and it should be clear.

**Comment by Zqinghaohh** [comment]
@liuyangzhuan Thank you very much! It helps me a lot!

One last question, you mentioned "this driver compresses a (Gaussian) kernel matrix with geometry point information (d-feature vectors as points in d-dimensional space)". Does it mean the matrix is reordered based on the column vectors in the matrix? 

So suppose we have an NxN matrix, the geometry point information is represented by each Nx1 vector (N-feature in this case) and after partitioning all column vectors, we now have a reordered matrix. Am I correct?

**Comment by liuyangzhuan** [comment]
For the kernel matrix A, it's something like A(i,j)=exp(-|x_i-x_j|), where x_i is length-d vector. So when you call
d_c_bpack_construct_init(&Npo, &Ndim, dat_ptr, nns_ptr,&nlevel, tree, perms, &myseg, &bmat, &option, &stats, &msh, &kerquant, &ptree, &C_FuncDistmn, &C_FuncNearFar, quant_ptr);
dat_ptr is a d*N length vector that stores [x_1^1, x_1^2,...,x_1^d,x_2^1,...] that is used to generate the permutation.

**Comment by Zqinghaohh** [comment]
Now I get it! Thanks!!!
