### ISSUE TITLE
How to chose the sampling parameters in STRUMPACK-Dense-1.1.1?

### ISSUE THREAD

**Issue by jerome92** [pghysels/STRUMPACK#9]
Hello author, when i used the STRUMPACK-Dense-1.1.1, i found the sampling parameters selection is important. But when the martix size different, how to chose the sampling parameters? (min_rand_HSS,lim_rand_HSS,inc_rand_HSS and max_rand_HSS)There is no description in the user‘s manual.Can you explain it to me? Thanks.

**Comment by pghysels** [comment]
Hi, Sorry for the delay.
This is explained in the manual of STRUMPACK-dense-1.1.0, in section 3.1.3.

The algorithm will adaptively try to determine the maximum rank. It starts with min_rand_HSS random vectors and then increment in steps of inc_rand_HSS, up to a maximum of max_rank_HSS. The algorithm stops when the computed rank is at least lim_rand_HSS less than the used number of random vectors. Ideally, you set min_rand_HSS to be slightly more (+lim_rand_HSS) than the actual rank. This will limit the number of adaptation steps. You can also increase inc_rand_HSS to minimize adaptation steps. Set max_rank_HSS big enough, so the algorithm does not stop before reaching the required tolerance.

**Comment by jerome92** [comment]
Ok, I know it.Thank you!
