### ISSUE TITLE
namespace "thrust" has no member "stable_sort_by_key"

### ISSUE THREAD

**Issue by sshiraiwa** [pghysels/STRUMPACK#90]
Dear Developer,
In case this is new...I am getting this error probably because I am using Cuda 12.1 (I didn't have this problem with
Cuda 11.7)
```
/src/sparse/ordering/NDBFS.cu(797): error: namespace "thrust" has no member
"stable_sort_by_key"
```
On Cuda 12.1, adding #include <thrust/sort.h> at the beginning of NDBFS.cu will fix the problem. But, probably doing so will cause a problem when one tryl to build on earlier version on Cuda?

**Comment by pghysels** [comment]
Thank you for reporting.
I'm still fixing a few issues for the new release. This reminds me to test with different CUDA versions before pushing the release out.
