### ISSUE TITLE
Input matrix NAN in ComputeRange

### ISSUE THREAD

**Issue by Zqinghaohh** [pghysels/STRUMPACK#91]
Dear developers,

As mentioned here https://github.com/pghysels/STRUMPACK/issues/89#issuecomment-1500668363, I decided to permute the matrix by myself by using cluster tree.

Then, I'm trying to construct HODLR matrix by a matrix-vector product routine. But even when I use the original dense matrix 'A' to generate such a product, 

```
op(A) * R=S
```

I still got the error "input matrix NAN in ComputeRange"

Please find the attached matrix file for test!
[A.txt](https://github.com/pghysels/STRUMPACK/files/11329370/A.txt)

And the code for reference (I'm using Petsc for mat-vec computing),
```
    auto AccessMatrixByMult2 = [&s, &A, &N](Trans op, const DenseMatrix<std::complex<double>> &Rs, DenseMatrix<std::complex<double>> &Ss)
    {
        Ss.resize(N, Rs.cols());

        std::vector<Vec> R;
        std::vector<Vec> S;
        DenseMatrixToVecs(R, Rs.rows(), Rs.cols(), Rs);
        DenseMatrixToVecs(S, Rs.rows(), Rs.cols(), Ss);
        S.clear();

        if (op == Trans::N)
        {
            for (int i = 0; i < Rs.cols(); ++i)
            {
                MatMult(A, R[i], S[i]);
            }
        } else if (op == Trans::T)
        {
            for (int i = 0; i < Rs.cols(); ++i)
            {
                Mat AT;
                MatCreateTranspose(A, &AT);
                MatMult(AT, R[i], S[i]);
            }
        } else if (op == Trans::C)
        {
            for (int i = 0; i < Rs.cols(); ++i)
            {
                MatConjugate(A);
                MatMult(A, R[i], S[i]);
            }
        }

        Ss.clear();
        VecsToDenseMatrix(S, Ss);
    };

    structured::ClusterTree t (N);
    t.refine(leafSize);
    HODLR::HODLRMatrix<std::complex<double>> H(c, t, AccessMatrixByMult2, opts);
```

Sincerely,
Qinghao

**Comment by liuyangzhuan** [comment]
The matrix looks fine. Maybe it can be helpful to test an all-one matrix (whose rank is 1)?

**Comment by Zqinghaohh** [comment]
Thanks for your helpful advice! I fixed it by removing resize and clear functions for DenseMatrix S!

**Comment by liuyangzhuan** [comment]
If AccessMatrixByMult2 does a dense matrix multiply with O(N^2) operations per matvec, the sketching-based construction will be slower. The element extraction-based construction will be way faster without the need to form the entire matrix.

**Comment by Zqinghaohh** [comment]
Thanks for your quick reply! I do have a AccessMatrixByMult1 which do not need to build the entire matrix explicitly. To do mat-vec product, I used shell matrix in petsc.

**Comment by liuyangzhuan** [comment]
If your matvec doesn't build the entire matrix explicitly, you will save from the N^2 memory requirement. But if you access all elements of the matrix, you will need O(N^2) flop counts per matvec, and if the rank is constant, your construction cost will be O(N^2logN). The sketching-based interface is meant for large matrices with a black-box O(NlogN) matvec function (e.g., with FFT or FMM). If that's not the case, you probably want to use the entry-based interface, whose CPU and memory both scale as O(NlogN) if the rank is constant.

**Comment by Zqinghaohh** [comment]
So, accessing all elements of the matrix is required by the randomized sampling algorithm, isn't it?

Overall, construction by max-vec costs O(N^2logN) while that by element evaluation costs only O(NlogN) for both CPU and memory efficiency. Am I understanding correct?

**Comment by liuyangzhuan** [comment]
"So, accessing all elements of the matrix is required by the randomized sampling algorithm, isn't it?" 
not necessarily. If you are working on method of moment, you could first construct a FMM representation of the impedance matrix, then use that as the matvec. The construction cost would be O(Nlog^2N), which is still a bit slower than construction by element evaluation.
 
"Overall, construction by max-vec costs O(N^2logN) while that by element evaluation costs only O(NlogN) for both CPU and memory efficiency. Am I understanding correct?"
Overall, the easiest and fastest way to construct HODLRD in method of moment is to use element evaluation.

**Comment by Zqinghaohh** [comment]
Thanks very much for your helpful advice!! Now I see!
